GRANT SELECT ON video TO PUBLIC;
GRANT SELECT ON VIDEO_LINK TO PUBLIC;
GRANT SELECT ON BROADCAST TO PUBLIC;
GRANT SELECT ON EPISODES TO PUBLIC;
GRANT SELECT ON PROGRAM TO PUBLIC;
GRANT SELECT ON WATCH_COUNT TO PUBLIC;
GRANT SELECT ON CATEGORY TO PUBLIC;
GRANT SELECT ON FULL_TOTAL TO PUBLIC;
GRANT SELECT ON TOTAL_WATCH_COUNT TO PUBLIC;
GRANT SELECT ON RECOMMENDATIONS_POPULAR TO PUBLIC;
GRANT SELECT ON RECOMMENDATIONS_OLD TO PUBLIC;

CREATE ROLE employe; --dans l'idee mais je ne peux pas le faire sous oracle
GRANT ALL ON VIDEO TO employe;
GRANT ALL ON VIDEO_LINK TO employe;
GRANT ALL ON BROADCAST TO employe;
GRANT ALL ON EPISODES TO employe;
GRANT ALL ON PROGRAM TO employe;
GRANT ALL ON WATCH_COUNT TO employe;
GRANT ALL ON PROGRAMS_FOLLOWED TO employe;
GRANT ALL ON LIKED_VIDEOS TO employe;
GRANT ALL ON WATCH_HISTORY TO employe;
GRANT ALL ON CATEGORY_INTERESTED TO employe;
GRANT ALL ON CATEGORY TO employe;
GRANT ALL ON ARCHIVES TO employe;
GRANT ALL ON ARCHIVES_LINK TO employe;
GRANT ALL ON ARCHIVES_BROADCAST TO employe;
GRANT ALL ON FULL_TOTAL TO employe;
GRANT ALL ON TOTAL_WATCH_COUNT TO employe;
GRANT ALL ON RECENT_WATCH_COUNT TO employe;
GRANT ALL ON RECOMMENDATIONS_LIKE TO employe;
GRANT ALL ON RECOMMENDATIONS_POPULAR TO employe;
GRANT ALL ON RECOMMENDATIONS_PROGRAM  TO employe;
GRANT ALL ON RECOMMENDATIONS_OLD TO employe;

CREATE ROLE users; --dans l'idee mais je ne peux pas le faire sous oracle
GRANT INSERT,SELECT,UPDATE ON REGISTERED_USER TO users;
GRANT INSERT,SELECT,UPDATE ON CATEGORY_INTERESTED TO users;
GRANT INSERT,SELECT ON WATCH_HISTORY TO users;
GRANT INSERT,SELECT,UPDATE ON LIKED_VIDEOS TO users;
GRANT INSERT,SELECT,UPDATE ON PROGRAMS_FOLLOWED TO users;
GRANT SELECT ON VIDEO TO users;
GRANT SELECT ON PROGRAM TO users;
GRANT SELECT ON EPISODES TO users;
GRANT SELECT ON BROADCAST TO users;
GRANT SELECT ON WATCH_COUNT TO users;
GRANT SELECT ON VIDEO_LINK TO users;
GRANT SELECT ON CATEGORY TO users;
GRANT SELECT ON FULL_TOTAL TO users;
GRANT SELECT ON RECOMMENDATIONS_LIKE TO users;
GRANT SELECT ON RECOMMENDATIONS_POPULAR TO users;
GRANT SELECT ON RECOMMENDATIONS_PROGRAM  TO users;
GRANT SELECT ON RECOMMENDATIONS_OLD TO users;

