CREATE VIEW TOTAL_WATCH_COUNT AS
	SELECT idVideo, SUM(ALL dayTotal) totalViews
	FROM WATCH_COUNT
	GROUP BY idVideo
	ORDER BY totalViews desc;
	
CREATE VIEW RECENT_WATCH_COUNT AS
	SELECT idVideo, SUM(ALL dayTotal) recentViews
	FROM WATCH_COUNT
	WHERE (current_date - watchDay) < 14
	GROUP BY idVideo
	ORDER BY recentViews desc;

CREATE VIEW FULL_TOTAL AS
	SELECT a.idVideo, a.totalViews, b.recentViews
	FROM TOTAL_WATCH_COUNT a
	LEFT JOIN RECENT_WATCH_COUNT b
	ON a.idVideo = b.idVideo;

CREATE VIEW RECOMMENDATIONS_LIKE AS
	SELECT videoName, duration, link
	FROM REGISTERED_USER
	NATURAL JOIN LIKED_VIDEOS
	NATURAL JOIN VIDEO
	NATURAL JOIN VIDEO_LINK;

CREATE VIEW RECOMMENDATIONS_POPULAR AS
	SELECT videoName, duration, link, recentViews
	FROM VIDEO
	NATURAL JOIN RECENT_WATCH_COUNT
	NATURAL JOIN VIDEO_LINK
	WHERE ROWNUM <= 1
	ORDER BY recentViews asc;

CREATE VIEW RECOMMENDATIONS_PROGRAM AS
	SELECT videoName, duration, link, episodeNb
	FROM REGISTERED_USER
	NATURAL JOIN PROGRAMS_FOLLOWED
	NATURAL JOIN PROGRAM
	NATURAL JOIN EPISODES
	NATURAL JOIN VIDEO
	NATURAL JOIN VIDEO_LINK;
	
CREATE VIEW RECOMMENDATIONS_OLD AS
	SELECT idVideo, videoName, duration, link, uploadDate
	FROM VIDEO
	NATURAL JOIN (
		SELECT idVideo, max(broadcastDate) uploadDate
		FROM BROADCAST
		GROUP BY idVideo
	)
	NATURAL JOIN VIDEO_LINK
	WHERE CURRENT_TIMESTAMP-uploadDate >= interval '12' day
