DROP VIEW FULL_TOTAL;
DROP VIEW TOTAL_WATCH_COUNT;
DROP VIEW RECENT_WATCH_COUNT;
DROP VIEW RECOMMENDATIONS_LIKE;
DROP VIEW RECOMMENDATIONS_POPULAR;
DROP VIEW RECOMMENDATIONS_PROGRAM;
DROP VIEW RECOMMENDATIONS_OLD;

